// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa675O9FD3XQnxO86skX6WY3qTylsZQuI',
    appId: '1:211071300765:web:c8105e7e19dc65490a1074',
    messagingSenderId: '211071300765',
    projectId: 'mayday-ad45b',
    authDomain: 'mayday-ad45b.firebaseapp.com',
    storageBucket: 'mayday-ad45b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxTSoRHMzJVa9KkHGT7OOmlnji9WNH0FU',
    appId: '1:211071300765:android:2eb957f5bc5a566a0a1074',
    messagingSenderId: '211071300765',
    projectId: 'mayday-ad45b',
    storageBucket: 'mayday-ad45b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKwwKL5pPId0oKdZdhJhedAyEoGDLZUsU',
    appId: '1:211071300765:ios:7931ad4f1d82823d0a1074',
    messagingSenderId: '211071300765',
    projectId: 'mayday-ad45b',
    storageBucket: 'mayday-ad45b.appspot.com',
    iosBundleId: 'com.example.mayday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKwwKL5pPId0oKdZdhJhedAyEoGDLZUsU',
    appId: '1:211071300765:ios:7931ad4f1d82823d0a1074',
    messagingSenderId: '211071300765',
    projectId: 'mayday-ad45b',
    storageBucket: 'mayday-ad45b.appspot.com',
    iosBundleId: 'com.example.mayday',
  );
}
